TRANSLATIONS = {
    'tr': {
        # Marka
        'brand_prefix': 'Cyber', 'brand_suffix': 'Aware',
        # Sidebar bölüm başlıkları
        'sec_general': 'Genel', 'sec_campaigns': 'Kampanyalar',
        'sec_targets': 'Hedefler', 'sec_templates': 'Şablonlar',
        # Navigasyon
        'nav_dashboard': 'Dashboard', 'nav_risk': 'Risk Analizi',
        'nav_campaigns': 'Tüm Kampanyalar', 'nav_new_campaign': 'Yeni Kampanya',
        'nav_templates': 'E-posta Şablonları', 'nav_targets': 'Tüm Hedefler',
        'nav_csv': 'CSV Import', 'nav_admin': 'Django Admin', 'nav_logout': 'Çıkış',
        # Login
        'login_heading': 'Kurumsal Güvenlik Farkındalık Platformu',
        'login_desc': 'Çalışanlarınızı gerçekçi phishing simülasyonlarıyla test edin, raporlayın ve eğitin.',
        'login_f1': 'Gerçekçi e-posta kampanyaları',
        'login_f2': 'Gerçek zamanlı risk analizi',
        'login_f3': 'PDF & Word otomatik raporlama',
        'login_f4': 'Grup bazlı hedef yönetimi',
        'login_welcome': 'Hoş geldiniz',
        'login_sub': 'Devam etmek için giriş yapın',
        'login_user': 'Kullanıcı Adı', 'login_pass': 'Şifre',
        'login_btn': 'Giriş Yap',
        'login_error': 'Kullanıcı adı veya şifre hatalı.',
        'login_footer': 'Erişim sorunları için sistem yöneticinize başvurun.',
        'login_copyright': 'Güvenlik Farkındalık Platformu',
        # Dashboard
        'stat_sent': 'Gönderilen', 'stat_opened': 'Açılan',
        'stat_clicked': 'Tıklayan', 'stat_submitted': 'Credential',
        'stat_sent_sub': 'toplam e-posta', 'stat_opened_sub': 'e-postayı açtı',
        'stat_clicked_sub': 'linke tıkladı', 'stat_submitted_sub': 'bilgi girdi',
        'dash_title': 'Dashboard', 'dash_sub': 'Tüm kampanyaların özet istatistikleri',
        'dash_chart1': 'Kampanya Karşılaştırması', 'dash_chart1_sub': 'Gönderilen / Açılan / Tıklayan / Credential',
        'dash_chart2': 'Genel Dağılım', 'dash_chart2_sub': 'Tüm kampanyalar',
        'dash_see_all': 'Tümünü gör',
        'th_campaign': 'Kampanya', 'th_status': 'Durum',
        'th_sent': 'Gönderilen', 'th_opened': 'Açılan',
        'th_clicked': 'Tıklayan', 'th_submitted': 'Credential',
        'th_click_rate': 'Tıklama Oranı', 'th_report': 'Rapor',
        'no_campaign_data': 'Henüz kampanya yok.',
        # Kampanyalar
        'page_campaigns': 'Kampanyalar',
        'page_campaigns_sub': 'Phishing simülasyon kampanyalarını yönetin',
        'btn_new_campaign': 'Yeni Kampanya',
        'th_template': 'Şablon', 'th_target': 'Hedef',
        'th_start': 'Başlangıç', 'th_end': 'Bitiş', 'th_actions': 'İşlemler',
        'st_scheduled': 'Planlandı', 'st_running': 'Çalışıyor', 'st_completed': 'Tamamlandı',
        'btn_launch': 'Başlat', 'btn_finish': 'Bitir', 'lbl_manual': 'Manuel',
        'no_campaigns': 'Henüz kampanya yok',
        'no_campaigns_sub': 'İlk kampanyanızı oluşturmak için',
        'no_campaigns_link': 'buraya tıklayın',
        # Hedefler
        'page_targets': 'Hedefler', 'btn_add_target': 'Hedef Ekle',
        'th_fullname': 'Ad Soyad', 'th_email': 'E-posta',
        'th_group': 'Grup', 'th_campaigns': 'Kampanya',
        'no_targets': 'Henüz hedef yok', 'lbl_manual_add': 'Manuel ekle →',
        'modal_add_title': 'Yeni Hedef Ekle',
        'field_firstname': 'Ad', 'field_lastname': 'Soyad', 'field_group': 'Grup',
        'lbl_optional': 'opsiyonel',
        'group_hint': 'Aynı grubu birden fazla kişiye vermek için aynı grup adını yaz.',
        'btn_cancel': 'İptal', 'btn_save': 'Kaydet', 'lbl_all': 'Tümü',
        # Risk
        'page_risk': 'Risk Analizi',
        'page_risk_sub': 'Hedef ve grup bazlı güvenlik açığı skorları',
        'lbl_total_targets': 'Toplam Hedef',
        'lbl_med_risk': 'Orta Risk', 'lbl_high_risk': 'Yüksek Risk',
        'sec_group_chart': 'Grup Bazlı Risk Karşılaştırması',
        'sec_group_chart_sub': 'Tıklama & credential oranları',
        'sec_group_table': 'Grup Analizi', 'sec_target_table': 'Hedef Risk Skorları',
        'th_person': 'Kişi', 'th_group_col': 'Grup', 'th_click': 'Tıklama',
        'th_cred': 'Credential', 'th_avg': 'Ort. Skor', 'th_risk': 'Risk',
        'th_score': 'Skor', 'th_clicked_col': 'Tıkladı', 'th_count': 'Kişi',
        'lbl_no_data': 'Henüz veri yok.',
        'risk_safe': 'Güvenli', 'risk_low': 'Düşük',
        'risk_medium': 'Orta', 'risk_high': 'Yüksek',
        'chart_click_lbl': 'Tıklama (%)', 'chart_cred_lbl': 'Credential (%)',
        'donut_opened': 'Açılan', 'donut_clicked': 'Tıklayan',
        'donut_submitted': 'Credential', 'donut_unopened': 'Açmadı',
        # Grup Detayı
        'page_group_detail': 'Grup Detayı', 'lbl_members': 'üye',
        'lbl_back_targets': 'Hedeflere Dön',
        'lbl_sent': 'Gönderildi', 'lbl_opened_ev': 'Açıldı',
        'lbl_clicked_ev': 'Tıkladı', 'lbl_submitted_ev': 'Bilgi Girdi',
        'lbl_not_in_campaign': 'Kampanyada yok',
        'no_campaign_in_group': 'Bu grup henüz bir kampanyada yer almadı.',
        # Yeni Kampanya
        'page_new_campaign': 'Yeni Kampanya',
        'page_new_campaign_sub': 'Simülasyon kampanyası oluşturun ve hedeflerinizi belirleyin',
        'btn_back': 'Geri',
        'lbl_basic_info': 'Temel Bilgiler',
        'lbl_campaign_name': 'Kampanya Adı',
        'lbl_email_template': 'E-posta Şablonu',
        'lbl_select_template': '— Şablon seçin —',
        'lbl_start_date': 'Başlangıç Tarihi',
        'hint_start_date': 'Zamanlayıcı bu tarihte otomatik başlatır.',
        'lbl_end_date': 'Bitiş Tarihi',
        'hint_end_date': 'Bu tarihte kampanya otomatik tamamlanır.',
        'lbl_manual_targets_sec': 'Manuel Hedef Seçimi',
        'lbl_manual_targets_hint': 'Grup seçilmediğinde aktif',
        'lbl_no_targets_found': 'Hedef bulunamadı.',
        'lbl_target_group_sec': 'Hedef Grup',
        'lbl_target_group_desc': 'Grup seçilirse o gruptaki tüm hedeflere gönderilir. Boş bırakılırsa soldaki manuel seçim geçerli olur.',
        'lbl_select_group': '— Grup seçilmedi —',
        'btn_launch_now': 'Kaydet ve Hemen Başlat',
        'btn_save_draft': 'Taslak Olarak Kaydet',
        'hint_draft': 'start_date geldiğinde zamanlayıcı otomatik başlatır.',
        'placeholder_campaign_name': 'ör. IT Güvenlik Testi — Ocak 2025',
        # Şablonlar sayfası
        'page_templates_sub': 'Şablonları önizleyin ve test gönderimleri yapın',
        'btn_new_template': 'Yeni Şablon',
        'lbl_no_templates': 'Henüz şablon yok',
        'lbl_add_from_admin': "Admin'den ekle →",
        'lbl_subject': 'Konu',
        'lbl_landing': 'Landing',
        'btn_preview': 'Önizle',
        'lbl_test_sent_ok': 'Test e-postası gönderildi',
        'lbl_test_send': 'Test e-postası gönder',
        'btn_test_send': 'Test Gönder',
        # CSV Import
        'page_csv_sub': 'Toplu hedef yüklemek için CSV dosyanızı yükleyin',
        'lbl_import_done': 'İçe aktarma tamamlandı.',
        'lbl_created': 'Yeni Eklendi',
        'lbl_updated': 'Güncellendi',
        'lbl_skipped': 'Atlandı',
        'lbl_upload_card': 'Dosya Yükle',
        'lbl_expected_format': 'Beklenen Format',
        'lbl_dropzone': 'Dosyayı sürükleyin veya tıklayın',
        'lbl_dropzone_sub': 'Yalnızca .csv dosyası',
        'btn_import': 'İçe Aktar',
        # Awareness sayfası
        'aw_title': 'Güvenlik Farkındalığı Testi',
        'aw_banner_h1': 'Bu bir Phishing Simülasyonuydu!',
        'aw_banner_p': 'Gerçek bir saldırıda değil, kurumsal güvenlik testindesiniz.',
        'aw_safe': '✅ Verileriniz kaydedilmedi — tamamen güvendesiniz.',
        'aw_tab1': '⚠ İpuçlarını Kaçırdınız',
        'aw_tab2': '🧠 Kendinizi Test Edin',
        'aw_tab3': '🛡 Korunma Rehberi',
        'aw_ind_intro': 'Bu e-postada fark edilebilecek phishing göstergeleri:',
        'aw_ind1_h': 'Gönderen Adresi Şüpheli',
        'aw_ind1_p': 'Gerçek kurumlar resmi alan adlarını kullanır. Sahte adresler benzer ama farklıdır (örn. @sirket-destek.com).',
        'aw_ind2_h': 'Aciliyet ve Baskı Dili',
        'aw_ind2_p': '"Hemen tıklayın", "hesabınız kapatılacak" gibi ifadeler panik yaratmaya yöneliktir.',
        'aw_ind3_h': 'Linkin Yönlendiği Adres',
        'aw_ind3_p': 'Fare ile linkin üzerine geldiğinizde alt çubukta görünen adres, kurumun resmi sitesiyle eşleşmiyor.',
        'aw_ind4_h': 'E-posta ile Şifre İstenmesi',
        'aw_ind4_p': 'Hiçbir meşru kurum e-posta ile şifrenizi istemez. Bu her zaman bir phishing işaretidir.',
        'aw_q1': '1. Tanımadığınız birinden acil yardım isteyen bir e-posta geldi. Ne yaparsınız?',
        'aw_q1a': 'Hemen cevap verir ve istenen bilgiyi paylaşırım.',
        'aw_q1b': 'E-postayı silerim ve IT departmanına bildiririm.',
        'aw_q1c': 'Linke tıklayıp ne istediğine bakarım.',
        'aw_q2': '2. Bir e-postadaki linkin gerçek mi sahte mi olduğunu nasıl anlarsınız?',
        'aw_q2a': 'Link metnine bakarak anlayabilirim.',
        'aw_q2b': 'Fareyle üzerine gelerek alt çubukta gerçek adresi kontrol ederim.',
        'aw_q2c': 'Tıklayıp açılan sayfaya bakarım.',
        'aw_q3': '3. IT departmanınız e-posta ile şifrenizi istedi. Ne yaparsınız?',
        'aw_q3a': 'Güvendiğim için şifremi gönderirim.',
        'aw_q3b': 'Şifremi e-posta yerine SMS ile gönderirim.',
        'aw_q3c': 'IT asla şifre istemez; bunu phishing olarak raporlarım.',
        'aw_btn_check': 'Cevapları Kontrol Et',
        'aw_score_0': 'Tekrar çalışmanız önerilir 📚',
        'aw_score_1': 'Tekrar çalışmanız önerilir 📚',
        'aw_score_2': 'İyi ama daha iyi olabilirsiniz 👍',
        'aw_score_3': 'Harika! Güvenlik uzmanısınız 🏆',
        'aw_tip1': '<strong>Gönderen adresini her zaman kontrol edin.</strong> Görünen ad değil, gerçek e-posta adresi önemlidir.',
        'aw_tip2': '<strong>Tıklamadan önce fareyle üzerine gelin.</strong> Linkin gittiği gerçek adresi kontrol edin.',
        'aw_tip3': '<strong>Şifrenizi hiçbir yere girmeyin.</strong> Platformlar e-posta ile şifre istemez.',
        'aw_tip4': '<strong>"Acil" mesajlara dikkat edin.</strong> Phishing e-postaları panik yaratmak için aciliyet hissi verir.',
        'aw_tip5': '<strong>Şüphelendiğinizde doğrulayın.</strong> Göndericiyi telefon ile arayarak teyit edin.',
        'aw_tip6': '<strong>IT departmanına bildirin.</strong> Şüpheli e-postaları hemen raporlayın — bu tüm kurumu korur.',
    },
    'en': {
        # Brand
        'brand_prefix': 'Cyber', 'brand_suffix': 'Aware',
        # Sidebar sections
        'sec_general': 'General', 'sec_campaigns': 'Campaigns',
        'sec_targets': 'Targets', 'sec_templates': 'Templates',
        # Navigation
        'nav_dashboard': 'Dashboard', 'nav_risk': 'Risk Analysis',
        'nav_campaigns': 'All Campaigns', 'nav_new_campaign': 'New Campaign',
        'nav_templates': 'Email Templates', 'nav_targets': 'All Targets',
        'nav_csv': 'CSV Import', 'nav_admin': 'Django Admin', 'nav_logout': 'Logout',
        # Login
        'login_heading': 'Corporate Security Awareness Platform',
        'login_desc': 'Test your employees with realistic phishing simulations, report and educate.',
        'login_f1': 'Realistic email campaigns',
        'login_f2': 'Real-time risk analysis',
        'login_f3': 'Automatic PDF & Word reporting',
        'login_f4': 'Group-based target management',
        'login_welcome': 'Welcome back',
        'login_sub': 'Sign in to continue',
        'login_user': 'Username', 'login_pass': 'Password',
        'login_btn': 'Sign In',
        'login_error': 'Invalid username or password.',
        'login_footer': 'Contact your system administrator for access issues.',
        'login_copyright': 'Security Awareness Platform',
        # Dashboard
        'stat_sent': 'Sent', 'stat_opened': 'Opened',
        'stat_clicked': 'Clicked', 'stat_submitted': 'Credential',
        'stat_sent_sub': 'total emails', 'stat_opened_sub': 'opened the email',
        'stat_clicked_sub': 'clicked the link', 'stat_submitted_sub': 'entered data',
        'dash_title': 'Dashboard', 'dash_sub': 'Summary statistics for all campaigns',
        'dash_chart1': 'Campaign Comparison', 'dash_chart1_sub': 'Sent / Opened / Clicked / Credential',
        'dash_chart2': 'Overview', 'dash_chart2_sub': 'All campaigns',
        'dash_see_all': 'See all',
        'th_campaign': 'Campaign', 'th_status': 'Status',
        'th_sent': 'Sent', 'th_opened': 'Opened',
        'th_clicked': 'Clicked', 'th_submitted': 'Credential',
        'th_click_rate': 'Click Rate', 'th_report': 'Report',
        'no_campaign_data': 'No campaigns yet.',
        # Campaigns
        'page_campaigns': 'Campaigns',
        'page_campaigns_sub': 'Manage your phishing simulation campaigns',
        'btn_new_campaign': 'New Campaign',
        'th_template': 'Template', 'th_target': 'Target',
        'th_start': 'Start', 'th_end': 'End', 'th_actions': 'Actions',
        'st_scheduled': 'Scheduled', 'st_running': 'Running', 'st_completed': 'Completed',
        'btn_launch': 'Launch', 'btn_finish': 'Finish', 'lbl_manual': 'Manual',
        'no_campaigns': 'No campaigns yet',
        'no_campaigns_sub': 'To create your first campaign,',
        'no_campaigns_link': 'click here',
        # Targets
        'page_targets': 'Targets', 'btn_add_target': 'Add Target',
        'th_fullname': 'Full Name', 'th_email': 'Email',
        'th_group': 'Group', 'th_campaigns': 'Campaigns',
        'no_targets': 'No targets yet', 'lbl_manual_add': 'Add manually →',
        'modal_add_title': 'Add New Target',
        'field_firstname': 'First Name', 'field_lastname': 'Last Name', 'field_group': 'Group',
        'lbl_optional': 'optional',
        'group_hint': 'Use the same group name to assign multiple people to the same group.',
        'btn_cancel': 'Cancel', 'btn_save': 'Save', 'lbl_all': 'All',
        # Risk
        'page_risk': 'Risk Analysis',
        'page_risk_sub': 'Security vulnerability scores by target and group',
        'lbl_total_targets': 'Total Targets',
        'lbl_med_risk': 'Medium Risk', 'lbl_high_risk': 'High Risk',
        'sec_group_chart': 'Group Risk Comparison',
        'sec_group_chart_sub': 'Click & credential rates',
        'sec_group_table': 'Group Analysis', 'sec_target_table': 'Target Risk Scores',
        'th_person': 'Person', 'th_group_col': 'Group', 'th_click': 'Click Rate',
        'th_cred': 'Credential', 'th_avg': 'Avg. Score', 'th_risk': 'Risk',
        'th_score': 'Score', 'th_clicked_col': 'Clicked', 'th_count': 'People',
        'lbl_no_data': 'No data yet.',
        'risk_safe': 'Safe', 'risk_low': 'Low',
        'risk_medium': 'Medium', 'risk_high': 'High',
        'chart_click_lbl': 'Click Rate (%)', 'chart_cred_lbl': 'Credential (%)',
        'donut_opened': 'Opened', 'donut_clicked': 'Clicked',
        'donut_submitted': 'Credential', 'donut_unopened': 'Not Opened',
        # Group Detail
        'page_group_detail': 'Group Detail', 'lbl_members': 'members',
        'lbl_back_targets': 'Back to Targets',
        'lbl_sent': 'Sent', 'lbl_opened_ev': 'Opened',
        'lbl_clicked_ev': 'Clicked', 'lbl_submitted_ev': 'Submitted',
        'lbl_not_in_campaign': 'Not in campaign',
        'no_campaign_in_group': 'This group has not participated in any campaign yet.',
        # New Campaign
        'page_new_campaign': 'New Campaign',
        'page_new_campaign_sub': 'Create a simulation campaign and define your targets',
        'btn_back': 'Back',
        'lbl_basic_info': 'Basic Information',
        'lbl_campaign_name': 'Campaign Name',
        'lbl_email_template': 'Email Template',
        'lbl_select_template': '— Select a template —',
        'lbl_start_date': 'Start Date',
        'hint_start_date': 'The scheduler will automatically start on this date.',
        'lbl_end_date': 'End Date',
        'hint_end_date': 'The campaign will automatically complete on this date.',
        'lbl_manual_targets_sec': 'Manual Target Selection',
        'lbl_manual_targets_hint': 'Active when no group is selected',
        'lbl_no_targets_found': 'No targets found.',
        'lbl_target_group_sec': 'Target Group',
        'lbl_target_group_desc': 'If a group is selected, emails are sent to all targets in that group. Otherwise, the manual selection on the left applies.',
        'lbl_select_group': '— No group selected —',
        'btn_launch_now': 'Save and Launch Now',
        'btn_save_draft': 'Save as Draft',
        'hint_draft': 'The scheduler will automatically start when start_date arrives.',
        'placeholder_campaign_name': 'e.g. IT Security Test — Jan 2025',
        # Templates page
        'page_templates_sub': 'Preview templates and send test emails',
        'btn_new_template': 'New Template',
        'lbl_no_templates': 'No templates yet',
        'lbl_add_from_admin': 'Add from Admin →',
        'lbl_subject': 'Subject',
        'lbl_landing': 'Landing',
        'btn_preview': 'Preview',
        'lbl_test_sent_ok': 'Test email sent',
        'lbl_test_send': 'Send test email',
        'btn_test_send': 'Send Test',
        # CSV Import
        'page_csv_sub': 'Upload your CSV file to bulk-import targets',
        'lbl_import_done': 'Import completed.',
        'lbl_created': 'Newly Added',
        'lbl_updated': 'Updated',
        'lbl_skipped': 'Skipped',
        'lbl_upload_card': 'Upload File',
        'lbl_expected_format': 'Expected Format',
        'lbl_dropzone': 'Drag or click to upload',
        'lbl_dropzone_sub': '.csv files only',
        'btn_import': 'Import',
        # Awareness page
        'aw_title': 'Security Awareness Test',
        'aw_banner_h1': 'This was a Phishing Simulation!',
        'aw_banner_p': 'You are not in a real attack — this is a corporate security test.',
        'aw_safe': '✅ Your data was not saved — you are completely safe.',
        'aw_tab1': '⚠ Clues You Missed',
        'aw_tab2': '🧠 Test Yourself',
        'aw_tab3': '🛡 Protection Guide',
        'aw_ind_intro': 'Phishing indicators in this email that could have been noticed:',
        'aw_ind1_h': 'Suspicious Sender Address',
        'aw_ind1_p': 'Legitimate organisations use official domains. Fake addresses look similar but differ (e.g. @company-support.com).',
        'aw_ind2_h': 'Urgency and Pressure Language',
        'aw_ind2_p': 'Phrases like "click immediately" or "your account will be closed" are designed to create panic.',
        'aw_ind3_h': 'Where the Link Points',
        'aw_ind3_p': "When you hover over the link, the address in the status bar doesn't match the organisation's official site.",
        'aw_ind4_h': 'Password Requested via Email',
        'aw_ind4_p': 'No legitimate organisation asks for your password by email. This is always a phishing sign.',
        'aw_q1': "1. You received an urgent help request from someone you don't know. What do you do?",
        'aw_q1a': 'I immediately reply and share the requested information.',
        'aw_q1b': 'I delete the email and report it to the IT department.',
        'aw_q1c': 'I click the link to see what they want.',
        'aw_q2': '2. How do you tell whether a link in an email is real or fake?',
        'aw_q2a': 'I can tell by looking at the link text.',
        'aw_q2b': 'I hover over it and check the real address in the status bar.',
        'aw_q2c': 'I click it and check the page that opens.',
        'aw_q3': '3. Your IT department asked for your password by email. What do you do?',
        'aw_q3a': 'I send my password because I trust them.',
        'aw_q3b': 'I send my password via SMS instead of email.',
        'aw_q3c': 'IT never asks for passwords — I report this as phishing.',
        'aw_btn_check': 'Check Answers',
        'aw_score_0': 'Further study recommended 📚',
        'aw_score_1': 'Further study recommended 📚',
        'aw_score_2': 'Good, but you can do better 👍',
        'aw_score_3': 'Excellent! You are a security expert 🏆',
        'aw_tip1': '<strong>Always check the sender address.</strong> The real email address matters, not the display name.',
        'aw_tip2': '<strong>Hover before you click.</strong> Check the real destination of the link.',
        'aw_tip3': "<strong>Never enter your password anywhere.</strong> Platforms don't ask for passwords via email.",
        'aw_tip4': '<strong>Be wary of "urgent" messages.</strong> Phishing emails create a sense of urgency to cause panic.',
        'aw_tip5': '<strong>Verify when in doubt.</strong> Confirm by calling the sender directly.',
        'aw_tip6': '<strong>Report to IT.</strong> Report suspicious emails immediately — it protects the entire organisation.',
    }
}
