# Generated by Django 5.2.7 on 2025-10-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'مجدولة'), ('Running', 'جارية'), ('Completed', 'منتهية')], default='Scheduled', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phish_manager.emailtemplate')),
                ('targets', models.ManyToManyField(to='phish_manager.target')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Sent', 'تم الإرسال'), ('Opened', 'تم الفتح'), ('Clicked', 'تم النقر'), ('Submitted', 'تم إدخال البيانات')], default='Sent', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unique_event_id', models.UUIDField(null=True, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phish_manager.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phish_manager.target')),
            ],
        ),
    ]
