# Generated by Django 5.2.7 on 2025-10-21 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unique_event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
