# Generated by Django 5.2.7 on 2025-10-21 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phish_manager', '0002_alter_event_unique_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
