# Generated by Django 5.2.7 on 2026-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_manager', '0003_alter_emailtemplate_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='was_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='was_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='was_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Completed', 'Completed')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Opened', 'Opened'), ('Clicked', 'Clicked'), ('Submitted', 'Submitted')], default='Sent', max_length=50),
        ),
    ]
