# Generated by Django 5.2.7 on 2026-03-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_manager', '0004_event_was_clicked_event_was_opened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='landing_page',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], default='linkedin', max_length=50),
        ),
    ]
